# --- SOLANA CONNECTION ---
SOLANA_RPC_URL=https://fittest-patient-pond.solana-mainnet.quiknode.pro/de9d37470b2873fedf650c074df9c9aa8519f5d9/

# --- MAIN WALLET (Holds funds, signs txs) ---
BOT_WALLET_ADDRESS=7BGXP14kLoS3DcTKAc6rrTxoWG1FbSMuEqBnyjtKW8md
BOT_WALLET_SECRET_KEY_BASE58=2Ev9jy6xVqu3MFAdwhgsHXG1NoRoDZD94o6zQJXY6Ap2XFzBrmCQZhNRi1xaLf3CUsjWeYaDa9Q5VjDkFyJ6dUV6

# --- SNIPER EXECUTION WALLET (Receives reinvestment) ---
SNIPER_WALLET_ADDRESS=CcLqa2zsAaVbsPWy1aRoojagNarXoD8jSKeSwQorBtsS

# --- BTC PAYOUT ADDRESSES ---
USER_BTC_ADDRESS=bc1ql37nntg829w2vyufpheg9wxdutl8m4zjvjudt2
RESERVE_BTC_ADDRESS=bc1q9k79mkx82h8e8awvda5slgw9sku0lyrf5mlaek

# --- JSON FILE PATHS (used by protocol engine) ---
PROTOCOL_JSON_PATH=./protocol.json
PROTOCOL_LOG_PATH=./protocol-log.json

# --- BLOCKONOMICS (for BTC transfers) ---
BLOCKONOMICS_API_KEY=vrjJr6QB5i5kTzWTQg7DL5SDplibq0F04EGKHgjLP58

# --- OPTIONAL / ADVANCED SETTINGS ---
SOL_REINVESTMENT_THRESHOLD_SOL=1.0
SOL_REINVESTMENT_TOPUP_AMOUNT_USD=100.00
MIN_SWAP_VALUE_USD=1
BTC_WITHDRAWAL_FEE_BUFFER_USD=20
AUTO_PAYOUT_USD_AMOUNT=100
AUTO_START_BOT=true

# --- JUPITER PUBLIC SWAP MODE (no key required) ---
JUPITER_API_KEY=public-lite
PLATFORM_SOLANA_ADDRESS=CcLqa2zsAaVbsPWy1aRoojagNarXoD8jSKeSwQorBtsS
SOLANA_PRIVATE_KEY_BASE58=2Ev9jy6xVqu3MFAdwhgsHXG1NoRoDZD94o6zQJXY6Ap2XFzBrmCQZhNRi1xaLf3CUsjWeYaDa9Q5VjDkFyJ6dUV6
